### ISSUE TITLE
ImportError: cannot import name 'window'

### ISSUE THREAD

**Issue by topher200** [artemave/tmux_super_fingers#1]
I'm getting an error when attempting to run the plugin.

![sticky](https://user-images.githubusercontent.com/206988/134218139-9a656b11-b389-4c21-a6be-0c3b6615b215.png)

OS: Ubuntu 21.04

.tmux.conf:

```
# remap prefix to Control + a
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# https://github.com/artemave/tmux_super_fingers
set -g @plugin 'artemave/tmux_super_fingers'
set -g @super-fingers-key f

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

Steps to reproduce:
1. Ctrl-a f
2. Observe window is opened with error

**Comment by artemave** [comment]
What's your python version?

**Comment by topher200** [comment]
```
$ python --version
Python 3.9.5
```

**Comment by artemave** [comment]
I am puzzled. Just switched to python 3.9.5 (was 3.9.8) on my Ubuntu 20 and everything still works.

**Comment by artemave** [comment]
Long shot, but is `python3 --verison`?

**Comment by topher200** [comment]
Interestingly, the version is slightly different. I wouldn't have expected that.

```
$ python3 --version
Python 3.9.6

$ python --version
Python 3.9.5
```

**Comment by topher200** [comment]
I'm able to reproduce the issue on a fresh gitpod instance. Here's what I did:

1. Navigate to https://gitpod.io/#https://github.com/artemave/tmux_super_fingers
2. Populate `~/.tmux.conf`:
```
# remap prefix to Control + a
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# https://github.com/artemave/tmux_super_fingers
set -g @plugin 'artemave/tmux_super_fingers'
set -g @super-fingers-key f

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```
3. Install
```
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
sudo apt install tmux
```
4. Run tmux (`tmux`)
5. `Prefix+I`
6. `Prefix+f`
7. Observe crash:

https://user-images.githubusercontent.com/206988/134385016-9457d529-ea9b-4b7b-857c-f946d916ba78.mp4


Note that the crash happens and the window closes immediately. I had to slow down the video to get the previous screenshot.

I've never shared a gitpod instance but it's possible you can see for yourself here: https://gitpod.io#snapshot/84db3c44-0b5c-405b-b370-84cc5a7a6fd0
Open that link, start tmux (if it's not in tmux already) and try `Ctrl+a f`. You should see the crash.

**Comment by topher200** [comment]
Actually, I slowed down the video above and observed that I'm getting a new unique error in the gitpod instance.

![image](https://user-images.githubusercontent.com/206988/134385507-5829b128-ddc8-4190-9d5a-7aa475db60c5.png)

**Comment by topher200** [comment]
It's very difficult to debug the issues because the window closes on error -- very tough to get debug information.

**Comment by artemave** [comment]
> Actually, I slowed down the video above and observed that I'm getting a new unique error in the gitpod instance.

So that is different error from your original one. And this time it's definitely caused by the python version. I get the same if I lock it to the stock ubuntu python3 version (3.8.10)

**Comment by artemave** [comment]
Yep

```
gitpod /workspace/tmux_super_fingers $ python --version
Python 3.8.12
```

**Comment by artemave** [comment]
If, however, you run `pyenv install 3.9.7` followed by `pyenv global 3.9.7` then the plugin works as expected

![image](https://user-images.githubusercontent.com/23721/134404431-6893c237-6962-4db6-b52a-78663dad2ca0.png)

**Comment by artemave** [comment]
Looks like this has been resolved.
