### ISSUE TITLE
[unresolved] Non-empty `$EDITOR` is not respected. Files are opened in FeatherPad.

### ISSUE THREAD

**Issue by simon-liebehenschel** [artemave/tmux_super_fingers#12]
On a clean Lubuntu the `$EDITOR` is empty. What I did:
1. Run `tmux` to start a new session.
2. `export EDITOR="/usr/bin/nano"`
3. `Ctrl + b`, `f`, then select a file to open. Files are opened in FeatherPad.

Basically, `$EDITOR` is not required because FeatherPad was launched even without touching it.

How can I switch to nvim?

---

I think that my problem is that I do not understand what does this mean:

> * running elsewhere within the same tmux session**

Should I start nvim somewhere before opening a file with  `Ctrl + b`, `f`?

### Versions
- tmux: Version: 3.2a-4ubuntu0.2
- Lubuntu 22.04

**Comment by artemave** [comment]
Interesting. Check out the "Gotchas" section of readme. Looks like you bumped into the same problem. It would be really helpful if you could get to the bottom of this.
