### ISSUE TITLE
Mouse mode scroll support

### ISSUE THREAD

**Issue by sergeylukin** [artemave/tmux_super_fingers#3]
Great plugin. Seems like it doesn't support scenario when pane has content above the screen and scrolling is involved to view the rest of the content. Are you planning on adding support for that?

**Comment by artemave** [comment]
True, you can't scroll while in fingers mode, but you can scroll up before that and then invoke fingers.

**Comment by artemave** [comment]
I've updated the readme to mention scrolling.
